---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Servers:
    - Portainer:
        href: https://10.18.210.10:9443
        ping: 10.18.210.201
        widget:
            type: portainer
            url: https://10.18.210.10:9443
            env: 2
            key: ptr_eeD5ReD3SRChrKdrNfLNjuPCwmYMHhSMlICt70P+e0I=

    - Killeen Auto Server 1 (Synology):
        href: https:10.18.210.10:5001
        widget:
            type: diskstation
            url: https://10.18.210.10:5001
            username: cwharton
            password: K1ll_$w1tch

    - Killeen Auto Server 2 (Fedora):
        href: https://10.18.210.12:9090
        ping: 10.18.210.12
    
    - DiskStation Database:
        href: https://10.18.210.6
        description: Manage WiFi access points

    - Ubiquity UniFi:
        href: https://10.18.210.6
        ping: 10.18.210.6

    - Automate (ConnectWise): 
        href: https://labtech.barcoment.com/automate/login
        icon: https://labtech.barcoment.com/automate/favicon.ico
        description: Barcom computer info 


- I.T Applications:
    - Support Tickets:
        href: https://support.killeenauto.local/scp/
        icon: http://support.killeenauto.local/images/oscar-favicon-32x32.png
        description: OSTicket agent console 
    
    - A.I.M.S. (Inventory):
        href: http://aims.killeenauto.local/
        description: Manage I.T. inventory 
    
    - Vonage (Phones):
        href: https://admin.vonage.com
        icon: https://admin.vonage.com/assets/images/Vicon_16@2x.png
        description: Mange VOIP phone system 
    
    - Google Admin:
        href: https://admin.google.com
        icon: https://ssl.gstatic.com/apps/cpanel/resources/logo/brand/admin_favicon.png
        description: Manage emails and Google docs 
    
    - Killeen Auto SIEM (Wazuh):
        href: https://siem.killeenauto.local/
        icon: http://siem.killeenauto.local/ui/favicons/favicon-32x32.png
        description: Security information and event management
    
    - Mimecast: 
        href: https://login.mimecast.com/"
        icon: https://login.mimecast.com/u/assets/images/connect_favicon.ico
        description: Manage emails security 

    - Microsoft Admin: 
        href: https://admin.microsoft.com
        icon: https://aadcdn.msftauth.net/shared/1.0/content/images/favicon_a_eupayfgghqiai7k9sol6lg2.ico
        description: Manage Office365 accounts 

- Monitors:
    - Ford Status:
        href: http://10.18.210.10:3001/status/ford
        widget:
            type: uptimekuma
            url: http://10.18.210.10:3001
            slug: ford

    - Service Status:
        href: http://10.18.210.10:3001/status/service
        widget:
            type: uptimekuma
            url: http://10.18.210.10:3001
            slug: service

    - Volkswagen Status:
        href: http://10.18.210.10:3001/status/volkswagen
        widget:
            type: uptimekuma
            url: http://10.18.210.10:3001
            slug: volkswagen

    - Hyundai Status:
        href: http://10.18.210.10:3001/status/hyundai
        widget:
            type: uptimekuma
            url: http://10.18.210.10:3001
            slug: hyundai

    - Certified Status:
        href: http://10.18.210.10:3001/status/certified
        widget:
            type: uptimekuma
            url: http://10.18.210.10:3001
            slug: certified

- Ford Networking:
    - Ford Gateway (Sonic Wall):
        href: https://10.18.210.201/
        ping: 10.18.210.201
    - Ford to Certified Bridge:
        href: https://10.10.11.10/
        ping: 10.10.11.10
    - Ford to Volkswagen Bridge:
        href: hhttps://10.10.11.12/
        ping: 10.10.11.12
    - Ford to Service Bridge:
        href: https://10.10.11.14/
        ping: 10.10.11.14
    - Ford Switch 1:
        href: https://10.18.210.225
        ping: 10.18.210.225
    - Ford Switch 2:
        href: https://10.18.210.247
        ping: 10.18.210.247
    - Ford Switch 3:
        href: http://10.18.210.223
        ping: 10.18.210.223
    - Ford Switch 4:
        href: https://10.18.210.229
        ping: 10.18.210.229
    - Ford Switch 5:
        href: https://10.18.210.249
        ping: 10.18.210.249

- Service Networking:
    - Service Gateway (Sonic Wall) [MDF]:
        href: https://108.178.98.22
        ping: 108.178.98.22
    - Service to Ford Bridge [IDF2]:
        href: https://10.10.11.15
        ping: 10.10.11.15   
    - Service Switch 1 [IDF2]:
        href: https://10.18.216.2
        ping: 10.18.216.2
    - Service Switch 2 [IDF2]:
        href: https://10.18.216.3
        ping: 10.18.216.3
    - Service Switch 3 [IDF1]:
        href: https://10.18.216.4
        ping: 10.18.216.4
    - Service Switch 4 [IDF1]:
        href: https://10.18.216.5
        ping: 10.18.216.5
    - Service Switch 5 [IDF1]:
        href: https://10.18.216.6
        ping: 10.18.216.6
    - Service Switch 6 [IDF1]:
        href: https://10.18.216.7
        ping: 10.18.216.7
    - Service Switch 7 [MDF]:
        href: https://10.18.216.8
        ping: 10.18.216.8
    - Service Switch 8 [MDF]:
        href: https://10.18.216.9
        ping: 10.18.216.9
    - Service Switch 9 [MDF]:
        href: https://10.18.216.10
        ping: 10.18.216.10

- Hyundai Networking:
    - Hyundai Switch 1:
        description: Network Closet
        href: https://10.18.210.248
        ping: 10.18.210.248
    - Hyundai Switch 2:
        description: Womans Restroom
        href: https://10.18.210.246
        ping: 10.18.210.246

- Volkswagen Networking:
    - Volkswagen Gateway (pfSence):
        href: https://10.18.215.1
        ping: 10.18.215.1
    - Volkswagen to Ford Bridge:
        href: https://10.10.11.13/
        ping: 10.10.11.13
    - Volkswagen Switch 1:
        href: https://10.18.215.2
        ping: 10.18.215.2
    - Volkswagen Switch 2:
        href: https://10.18.215.3
        ping: 10.18.215.3
    - Volkswagen Switch 3:
        href: https://10.18.215.4
        ping: 10.18.215.4
    - Volkswagen Switch 4:
        href: https://10.18.215.5
        ping: 10.18.215.5

- Certified Networking:
    - Certified Gateway (pfSence):
        href: https://10.18.213.2
        ping: 10.18.213.2
    - Certified to Ford Bridge:
        href: https://10.10.11.11/
        ping: 10.10.11.11
    - Certified Switch 1:
        href: https://10.18.213.5
        ping: 10.18.213.5


- Security Cameras:
    - Cameras Status:
        href: http://10.18.210.10:3001/status/cameras
        widget:
            type: uptimekuma
            url: http://10.18.210.10:3001
            slug: cameras

    - Pro-Vigis Portal:
        href: https://portal.pro-vigil.info/
        description: Manage Pro-Vigil Account
    - Pro-Vigis Ford:
        href: https://f1359-nas2.us6.quickconnect.to/
    - Pro-Vigis Certified:
        href: https://f1356-nas1.us5.quickconnect.to/
    - Pro-Vigis Service:
        href: https://f1355-nas1.us5.quickconnect.to/
    - Pro-Vigis Volkswagen:
        href: https://f1357-nas1.us1.quickconnect.to/