---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- greeting:
    text_size: xl
    text: Killeen Auto

- datetime:
    text_size: xl
    format:
        dateStyle: short
        timeStyle: short
        hour12: true

- resources:
    label: Killeen Auto Server 1
    cpu: true
    memory: true
    cputemp: true
    units: imperial # only used by cpu temp
    refresh: 3000 # optional, in ms
- resources:
    label: Uptime
    uptime: true
- resources:
    label: Storage
    disk: /

- openmeteo:
    label: Killeen 
    latitude: 31.0863
    longitude: -97.7061
    units: imperial
    cache: 5 